apiVersion: apps/v1
kind: Deployment
metadata:
  name: passport
  labels:
    app: passport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: passport
  template:
    metadata:
      labels:
        app: passport
    spec:
      containers:
        - name: passport
          image: plifis/job4j_passport
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgresdb-secret
                  key: postgres-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresdb-secret
                  key: postgres-password
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: postgresdb-configmap
                  key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: passport-service
spec:
  selector:
    app: passport
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32111